//
//  YZIconKit.h
//  Yichi Zhang
//
//  Created by Yichi Zhang on 17/10/2014.
//  Copyright (c) 2014 Yichi Zhang. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface YZIconKit : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* peopleTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* cameraTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* infoTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* flaskTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* hookTurnTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* koalaTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* emuTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* kangarooTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* wildHorseTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* camelTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* wombatTargets;

// Drawing Methods
+ (void)drawPeople;
+ (void)drawCamera;
+ (void)drawInfo;
+ (void)drawFlask;
+ (void)drawHookTurn;
+ (void)drawKoala;
+ (void)drawEmu;
+ (void)drawKangaroo;
+ (void)drawWildHorse;
+ (void)drawCamel;
+ (void)drawWombat;

// Generated Images
+ (UIImage*)imageOfPeople;
+ (UIImage*)imageOfCamera;
+ (UIImage*)imageOfInfo;
+ (UIImage*)imageOfFlask;
+ (UIImage*)imageOfHookTurn;
+ (UIImage*)imageOfKoala;
+ (UIImage*)imageOfEmu;
+ (UIImage*)imageOfKangaroo;
+ (UIImage*)imageOfWildHorse;
+ (UIImage*)imageOfCamel;
+ (UIImage*)imageOfWombat;

@end
